/**
 * Compile-time contract for notification jobs: what NotificationService
 * enqueues and what the notification worker receives.
 *
 * Types only. No validation, no logging, no infrastructure imports.
 *
 * Job data crosses Redis as JSON, so every field is plain serializable data.
 * Timestamps are ISO 8601 strings, not Date: a Date would arrive in the
 * worker as a string while the type claimed otherwise.
 *
 * Adding a notification type: add a payload interface and one entry in
 * NotificationPayloadMap. NotificationType and NotificationJobData derive
 * from the map.
 */

/** The user a notification is addressed to. */
export interface NotificationRecipient {
  /** Use this, not `email`, when logging about a job. */
  readonly userId: string;
  /** PII: do not log. */
  readonly email: string;
  readonly firstName: string;
}

export interface AccountActivationPayload {
  readonly recipient: NotificationRecipient;
  /**
   * SENSITIVE. The raw (unhashed) token from AuthService.issueActivationToken();
   * only its hash is stored in the database. Whoever holds it can activate the
   * account and set its password until it expires. Use it only to build the
   * activation link. Never log it, never include it in an error message, and
   * never copy it into any other record.
   */
  readonly rawActivationToken: string;
}

export interface PasswordResetPayload {
  readonly recipient: NotificationRecipient;
  /**
   * SENSITIVE. The raw (unhashed) password-reset token generated by
   * AuthService.requestPasswordReset(). Same handling rules as
   * rawActivationToken: link-building only, never logged or persisted elsewhere.
   */
  readonly rawResetToken: string;
}

/** Deliberately carries no credentials of any kind. */
export interface PasswordChangedPayload {
  readonly recipient: NotificationRecipient;
  /** ISO 8601. */
  readonly changedAt: string;
}

/** Security events AuthService already detects today. Extend as new ones appear. */
export type SecurityAlertEvent = 'ACCOUNT_LOCKED' | 'REFRESH_TOKEN_REUSE';

export interface SecurityAlertPayload {
  readonly recipient: NotificationRecipient;
  readonly event: SecurityAlertEvent;
  /** ISO 8601. */
  readonly occurredAt: string;
  /** Personal data: do not log. Absent when the request metadata had none. */
  readonly ipAddress?: string | undefined;
  /** Personal data: do not log. */
  readonly userAgent?: string | undefined;
}

/** Single source of truth: notification type -> its exact payload. */
export interface NotificationPayloadMap {
  ACCOUNT_ACTIVATION: AccountActivationPayload;
  PASSWORD_RESET: PasswordResetPayload;
  PASSWORD_CHANGED: PasswordChangedPayload;
  SECURITY_ALERT: SecurityAlertPayload;
}

export type NotificationType = keyof NotificationPayloadMap;

/**
 * The data stored on each BullMQ job. Named `...JobData` because BullMQ's `Job`
 * is the runtime object that wraps this. A discriminated union: `type` selects
 * the exact `payload`, so ACCOUNT_ACTIVATION cannot carry a PasswordResetPayload.
 */
export type NotificationJobData = {
  [K in NotificationType]: {
    readonly type: K;
    readonly payload: NotificationPayloadMap[K];
  };
}[NotificationType];
